Signed-off-by: MICHAELBOWLER michaelb@ie.ibm.com
IBM/continuous-delivery-go-sdk pull request #11
Opened 2022-08-19 15:55 UTC by michaelbowler

## PR summary
ID edits for README as per https://github.ibm.com/org-ids/ua-issues/issues/1939

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x ] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [x ] Tests for the changes have been added (for bug fixes / features)
- [x ] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [x ] Documentation content changes
- [ ] Other (please describe)

## What is the current behavior?  

## What is the new behavior?  

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x ] No

## Other information

2022-08-29 11:42 UTC, michaelbowler commented
@gmarjoram @cbrealey - could we reviewmerge this PR if OK?

2022-08-30 13:23 UTC, gmarjoram commented
@michaelbowler is the table label meant to be under the table ?
![image](https://user-images.githubusercontent.com/7964963/187448244-f4de5b10-d3db-45a3-aeef-e243489e687e.png)

2022-08-30 13:31 UTC, michaelbowler commented
@gmarjoram - hum, yes. Let me amend...

2022-08-30 13:34 UTC, michaelbowler commented
@gmarjoram ... better:

![image](https://user-images.githubusercontent.com/5979512/187450825-01c7de01-5d64-4bc7-97f2-524ca8510c4b.png)

2022-08-30 13:41 UTC, gmarjoram approved these changes
I'm ok with this but would like @cbrealey to also have a quick look

2022-09-06 12:01 UTC, michaelbowler commented
@briangleeson - not sure of your process here.  Can I resolve conflicts and merge now?

2022-09-06 16:37 UTC, briangleeson commented
@michaelbowler you can go ahead and resolve the merge conflicts. From reading above, I think we're just waiting for approval from @cbrealey on the changes, then can merge

2022-09-06 20:21 UTC, briangleeson requested changes

2022-09-07 10:53 UTC, michaelbowler commented on README.md
> +The current version of this SDK: 1.0.0
OK NP @briangleeson

2022-09-07 12:46 UTC, briangleeson approved these changes

2022-09-08 20:15 UTC, cbrealey approved these changes
Changes look excellent, and apologies for the delay on my part. Only side comment is that this README may be originally been based on a template, in which event we should seek out and update that template so that other IBM SDK repos' READMEs may benefit.

2022-09-09 06:23 UTC, merged

2022-09-09 08:07 UTC, michaelbowler commented
Thanks @cbrealey - can we now close https://github.ibm.com/org-ids/ua-issues/issues/1939 also?

I'll also hunt for and change the source template.